/*
 * Generated by Bluespec Compiler, version 2023.07 (build 0eb551d)
 * 
 * On Sun Sep 24 13:19:54 CST 2023
 * 
 */

/* Generation options: keep-fires */
#ifndef __model_mkPitchAdjustTest_h__
#define __model_mkPitchAdjustTest_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkPitchAdjustTest.h"

/* Class declaration for a model of mkPitchAdjustTest */
class MODEL_mkPitchAdjustTest : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkPitchAdjustTest *mkPitchAdjustTest_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkPitchAdjustTest();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(char const **name, char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkPitchAdjustTest();
}

#endif /* ifndef __model_mkPitchAdjustTest_h__ */
